显示uosc菜单	script-binding uosc/menu

加载 (&L)
	剪贴板URL (&C)		update-clipboard text; loadfile ${clipboard/text}; show-text '+ ${clipboard/text}'
轨道聚合列表	$tracks

导航 (&N)
	播放列表 (&P)		$playlist
	版本列表 (&E)		$editions
	章节列表 (&C)		$chapters

	视频轨列表 (&V)		$video-tracks
	音频轨列表 (&A)		$audio-tracks
	字幕轨列表 (&S)		$sub-tracks

	播放列表乱序重排 (&R)	playlist-shuffle
播放 (&P)
	上一帧						frame-back-step
	下一帧						frame-step
	设置/清除 AB循环点 (&A)		ab-loop
	速度 (&S)
		50%			set speed 0.5	checked=speed == 0.5
		100% (&1)	set speed 1		checked=speed == 1
		150% (&2)	set speed 1.5	checked=speed == 1.5
		200% (&3)	set speed 2		checked=speed == 2

	音量 -		add volume -1
	音量 +		add volume  1

	音频预载 100ms		add audio-delay -0.1
	音频延迟 100ms		add audio-delay  0.1
	字幕预载 100ms		add sub-delay -0.1
	字幕延迟 100ms		add sub-delay  0.1

	重置 音频与字幕同步 (&R)	set audio-delay 0; set sub-delay 0

VF 滤镜 (&F)
	清空 (&C)	vf clr ""

	预设 补帧 MVTools_快速			vf set vapoursynth="~~/vs/MEMC_MVT_LQ.vpy"
	预设 补帧 RIFE_DX12				vf set vapoursynth="~~/vs/MEMC_RIFE_DML.vpy"
	预设 补帧 DRBA_DX12				vf set vapoursynth="~~/vs/MEMC_DRBA_DML.vpy"
	预设 补帧 RIFE_RTX (DLC-vsNV)	vf set vapoursynth="~~/vs/MEMC_RIFE_NV.vpy"
	预设 补帧 DRBA_RTX (DLC-vsNV)	vf set vapoursynth="~~/vs/MEMC_DRBA_NV.vpy"

	预设 自定义AI UAI_DX12				vf set vapoursynth="~~/vs/MIX_UAI_DML.vpy"
	预设 自定义AI UAI_RTX (DLC-vsNV)	vf set vapoursynth="~~/vs/MIX_UAI_NV_TRT.vpy"
着色器 (&G)
	清空 (&C)	change-list glsl-shaders clr ""

	开关 LUMA: Ani4Kv2		change-list glsl-shaders toggle "~~/shaders/Ani/Ani4Kv2_ArtCNN_C4F32_i2.glsl"
	开关 LUMA: AniSD		change-list glsl-shaders toggle "~~/shaders/Ani/AniSD_ArtCNN_C4F32_i4.glsl"
	开关 LUMA: FSRCNNX		change-list glsl-shaders toggle "~~/shaders/FSRCNNX/FSRCNNX_x2_16_0_4_1.glsl"
	开关 LUMA: NNEDI3		change-list glsl-shaders toggle "~~/shaders/EDI/nnedi3_nns64_win8x4.glsl"

	开关 MAIN: A4K_重建		change-list glsl-shaders toggle "~~/shaders/Anime4K/Anime4K_Restore_CNN_L.glsl"
	开关 MAIN: A4K_放大		change-list glsl-shaders toggle "~~/shaders/Anime4K/Anime4K_Upscale_GAN_x2_M.glsl"
	开关 MAIN: A4K_配置Q	change-list glsl-shaders toggle "~~/shaders/Anime4K/Anime4K_AIO_optQ.glsl"

	开关 POSTKERNEL: QCOM_主缩放锐化 RT (*)		change-list glsl-shaders toggle "~~/shaders/QCOM/QCOM_SGEDS_ms_RT.glsl"

	开关 SCALED: 自适应锐化lite RT		change-list glsl-shaders toggle "~~/shaders/Adaptive_sharpen/Adaptive_sharpen_lite_RT.glsl"

截屏 (&K)
	窗口-无OSD (&S)		screenshot scaled+subtitles
	窗口 (&W)			screenshot window
	原始 (&V)			screenshot video

视频 (&V)
	切换 解码模式 (&H)		cycle-values hwdec "auto" "auto-copy" "no"
	切换 去色带状态 (&D)	cycle deband		checked=deband
	切换 去隔行状态 (&I)	cycle deinterlace	checked=deinterlace_active
	切换 自动校色			cycle icc-profile-auto
	切换 时间码解析模式		cycle correct-pts
	均衡器 (&E)
		对比度 -	add contrast -1
		对比度 +	add contrast  1
		亮度 -		add brightness -1
		亮度 +		add brightness  1
		伽马 -		add gamma -1
		伽马 +		add gamma  1
		饱和度 -	add saturation -1
		饱和度 +	add saturation  1
		色相 -		add hue -1
		色相 +		add hue  1

		重置 全部 (&R)		set contrast 0 ; set brightness 0 ; set gamma 0 ; set saturation 0 ; set hue 0

工具 (&T)
	按键绑定列表				script-binding select/select-binding
	常驻显示统计信息 (&S)		script-binding display-stats-toggle
	显示OSD命令行/控制台 (&C)	script-binding commands/open
	清除已记录的属性值			script-message-to save_global_props clean_data
	切换 窗口边框 (&B)			cycle border	checked=border
	切换 窗口置顶 (&O)			cycle ontop		checked=ontop
	按键名检测					script-binding input_plus/input_test_toggle

	打开select总菜单 (&M)		script-binding select/menu
	打开select分菜单-属性列表	script-binding select/show-properties
	音频输出设备列表 (&A)		$audio-devices

关于 (&I)
	项目主页 (&H)	script-message-to input_plus lazy-helper 0
	mpv手册 (&M)	script-message-to input_plus lazy-helper 1
	中文手册 (&C)	script-message-to input_plus lazy-helper 2
	FAQ (&F)		script-message-to input_plus lazy-helper 3
	滤镜指北		script-message-to input_plus lazy-helper 4
	着色器指南		script-message-to input_plus lazy-helper 5

停止 (&X)		stop	disabled=idle_active
退出mpv (&Q)	quit
