# Zack Ver.260309
include="~~/script-opts.conf"
#log-file="~~desktop/mpv_PlayKit.log" #只在除錯時開啟，平時不建議（會持續寫入磁碟）。
# save-position-on-quit=yes #離開時自動保存播放位置

#音訊
audio-channels=5.1,stereo
audio-spdif=ac3,dts,dtshd

#MEMC
vf='vapoursynth="~~/vs/MEMC_RIFE_DML.vpy"' #極致品質-極致消耗-動畫原始節奏與他無關 
# vf='vapoursynth="~~/vs/MEMC_DRBA_DML.vpy"' #品質模型-中等消耗-嘗試保留動畫原始節奏 
# vf='vapoursynth="~~/vs/MEMC_MVT_LQ.vpy"' #效能模型-最低消耗

#著色器
glsl-shaders-append=~~/shaders/ESRGAN/the_database_AnimeJaNaiV2L1_x2.glsl#放大2倍 重建線條 高銳利
#若效能不足，可改用以下著色器
# glsl-shaders-append=~~/shaders/Anime4K/Anime4K_Restore_CNN_M.glsl #伪影修复、锐化
# glsl-shaders-append=~~/shaders/Anime4K/Anime4K_Upscale_CNN_x2_L.glsl #放大2倍

#內建算法
correct-downscaling=yes
cscale=ewa_lanczos
dscale=mitchell
interpolation=no # 禁用插值；螢幕若無對應 FPS 或其整數倍的刷新率，需手動設定自訂 Hz
linear-downscaling=yes
scale=ewa_lanczos
sigmoid-upscaling=yes

#配置
ao=wasapi
audio-file-auto=fuzzy
autocreate-playlist=same
autofit=80%
border=no
deinterlace=auto
demuxer-max-bytes=512MiB
directory-mode=ignore
dither-depth=10
gpu-api=vulkan
gpu-context=winvk
gpu-shader-cache-dir="~~/_cache/shader"
hidpi-window-scale=yes
hr-seek-framedrop=no
hwdec=vulkan
icc-cache-dir="~~/_cache/icc"
input-builtin-bindings=no
loop-playlist=inf
osc=no
osd-bar-align-y=-1
osd-bar-h=2
osd-bar-w=100
osd-on-seek=msg
osd-playing-msg="${filename}"
screenshot-high-bit-depth=yes
screenshot-template="~~desktop/MPV-%P-N%n"
slang=cht,tc,chi,zh,zh-tw
sub-auto=fuzzy
sub-file-paths=sub;Subs;subtitles
subs-fallback=yes
swapchain-depth=3
video-sync=audio
vo=gpu-next
volume-max=100
vulkan-async-compute=yes
vulkan-swap-mode=fifo
watch-later-dir="~~/_cache/watch_later"
watch-later-options=start,vid,aid,sid

# 當音軌大於2聲道時，即時編碼成 AC3 輸出。
[Multi-Channel]
profile-cond='p["audio-params/channel-count"]>2'
af=lavcac3enc

# 當碼率低於 3000kbps 時自動啟用高強度的去色帶濾鏡。
[deband-bitrate]
profile-desc=基于码率的自动去色带
profile-cond=((p.file_size/1024)*8)/p.duration<=3000
profile-restore=copy
deband=yes
deband-iterations=4 # 增加處理次數
deband-threshold=64 # 更強去色帶
deband-range=20 # 提高去色帶範圍
deband-grain=12 # 更多噪點，保留細節

[HDR-Xiaomi_S_MiniLED]
profile-desc=Xiaomi_S_MiniLED_HDR
profile-cond='p["video-params/sig-peak"]>1'
profile-restore=copy
blend-subtitles=no
hdr-compute-peak=yes # 動態計算峰值亮度
image-subs-hdr-peak=10000
sub-hdr-peak=100 # HDR字幕亮度限制
target-peak=1200 # 小米1200nits 
target-prim=bt.2020 # 針對BT.2020色域
target-trc=pq
tone-mapping=bt.2446a # 更精確的 HDR 映射
tone-mapping-param=0.8 # 適配Mini LED高對比