###不支持参数后注释，须另起一行
###不允许选项和值之间存在多余的空格

# 禁用的界面元素，多个值之间用半角逗号分隔。当前以下元素支持受用户自行禁用
# window_border,top_bar,timeline,controls,volume,idle_indicator,audio_indicator,buffering_indicator,pause_indicator
disable_elements=window_border,top_bar,timeline,controls,volume,idle_indicator,audio_indicator,buffering_indicator,pause_indicator

# 空闲是否显示logo
idlescreen=no